### This script creates a prior to serve as a prior for the 
### individualized network metrics generated by priorICA
###
### Ellyn Butler
### July 6, 2025 - July 8, 2025

library(dplyr)

# Input directory
indir <- '/projects/b1108/projects/personalized_versus_group/data/processed/neuroimaging/'
#indir <- '~/Documents/Northwestern/projects/personalized_versus_group/data/processed/neuroimaging/'

# Output directory
outdir <- '/projects/b1108/projects/personalized_versus_group/data/processed/neuroimaging/prior/'
#outdir <- '~/Documents/Northwestern/projects/personalized_versus_group/data/processed/neuroimaging/prior/'

# Packages
#devtools::install_github('mandymejia/fMRItools', '0.4') # Need dev version, not CRAN
library(fMRItools)
stopifnot(utils::packageVersion('fMRItools') >= '0.4.4')
#install.packages('ciftiTools')
library(ciftiTools)
ciftiTools.setOption('wb_path', '/projects/b1108/software/workbench')
#devtools::install_github('mandymejia/priorICAr', '8.0') # Need dev version, not CRAN
#^ try again
library(BayesBrainMap)


## -----------------------------------------------------------------------------


save(list=ls(), file=paste0(outdir, 'estimate_prior_args.rda'))

temp_subjs <- read.csv(paste0(indir, 'tabulated/prior_subjects.csv'))

GPARC <- readRDS(paste0(outdir, '/GPARC.rds'))

print('Resample GPARC')

GPARC <- resample_cifti(GPARC, resamp_res = 10000)

print('Get the paths to the maximally postprocessed resting state data.')
Sys.setenv('R_MAX_VSIZE'=32000000000)
paths <- c()
sesid <- 1
for (j in 1:nrow(temp_subjs)) { 
  subid <- temp_subjs[j, 'subid']
  path <- c(system(paste0('find ', indir, 'surf/sub-', subid, '/ses-', sesid, '/func/ ', 
        '-name "*_task-chatroom_run-01_space-fsLR_desc-maxpostproc_bold.dscalar.nii"'), intern=TRUE))
  paths <- c(paths, path)
}

print('Estimate prior.') 
temp <- estimate_prior(
  paths,
  GPARC, 
  hpf = 0, 
  scale = 'local',
  brainstructures = c('left', 'right'),
  GSR = FALSE,
  FC = FALSE,
  scale_sm_surfL = load_surf('left'),
  scale_sm_surfR = load_surf('right'), 
  verbose = TRUE#, usePar=4, wb_path=wb_path
) 

saveRDS(temp, paste0(outdir, 'prior.rds'))


#plot(temp, idx=1:17, fname=paste0('/Users/flutist4129/Documents/Northwestern/projects/personalized_versus_group/plots/temp_maxpostproc_sub-ses2_ses-rand_', 1:17))